package com.todolist.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * [TodoItem]
 * This data class is used to create the schema of the table
 * @property id : autogenerated id
 * @property text :  todo text field text
 */
@Entity(tableName = "todo_items")
data class TodoItem(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val text: String
)
